name: GreenText
version: 1.1
main: me.MFHKiwi.GreenText.GreenText
description: A 4chan green text plugin for CraftBukkit 1060.
author: MFHKiwi
commands:
   gt:
      description: Print information about GreenText.
      usage: /gt
      aliases: [greentext, gtext]